// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFJbRwE01vUWNR-CAfn-LojuVsoV8K9c0',
    appId: '1:744471895908:web:4e0c27a62d9f6c75976471',
    messagingSenderId: '744471895908',
    projectId: 'upfiesta-6b611',
    authDomain: 'upfiesta-6b611.firebaseapp.com',
    storageBucket: 'upfiesta-6b611.firebasestorage.app',
    measurementId: 'G-PG8TMHJ5Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKfKkU3C_viP7YMqRYUAb7hZrXVMcDJI4',
    appId: '1:744471895908:android:ad74ed273eaebc6d976471',
    messagingSenderId: '744471895908',
    projectId: 'upfiesta-6b611',
    storageBucket: 'upfiesta-6b611.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiNGEj-gKx882Zc9DRvsq4xSrWD8ZzIb0',
    appId: '1:744471895908:ios:0ca8f1ef57b3c063976471',
    messagingSenderId: '744471895908',
    projectId: 'upfiesta-6b611',
    storageBucket: 'upfiesta-6b611.firebasestorage.app',
    iosBundleId: 'com.example.upFiestaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiNGEj-gKx882Zc9DRvsq4xSrWD8ZzIb0',
    appId: '1:744471895908:ios:0ca8f1ef57b3c063976471',
    messagingSenderId: '744471895908',
    projectId: 'upfiesta-6b611',
    storageBucket: 'upfiesta-6b611.firebasestorage.app',
    iosBundleId: 'com.example.upFiestaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFJbRwE01vUWNR-CAfn-LojuVsoV8K9c0',
    appId: '1:744471895908:web:22687497986aafcd976471',
    messagingSenderId: '744471895908',
    projectId: 'upfiesta-6b611',
    authDomain: 'upfiesta-6b611.firebaseapp.com',
    storageBucket: 'upfiesta-6b611.firebasestorage.app',
    measurementId: 'G-FB18N6FMWC',
  );
}
